#物品id对应的中文名称
#如果物品带有材质则先带材质匹配，没有再分开匹配
flint_and_steel: 打火石
apple: 苹果
bow: 弓
arrow: 箭
coal: 煤炭
diamon: 钻石
iron_ingot: 铁锭
gold_ingot: 金锭
stick: 木棍
bowl: 碗
mushroom_stew: 蘑菇煲
wooden: 木
stone: 石
iron: 铁
diamond: 钻石
golden: 金
hoe: 锄
pickaxe: 镐
axe: 斧
shovel: 锹
sword: 剑
helmet: 头盔
chestplate: 胸甲
leggings: 护腿
boots: 靴子
chainmail: 锁链
leather: 皮革
chicken: 生鸡肉
cod: 鳕鱼
carrot: 胡萝卜
bucket: 桶
